/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  bgVideo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  bgFallbackImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroTitle?: LocalizedString;
  heroSubtitle?: LocalizedString;
  heroBanner?: Banner;
  servicesTitle?: LocalizedString;
  servicesSubtitle?: LocalizedString;
  servicesList?: Array<{
    _key: string;
  } & Service>;
  servicesBanner?: Banner;
  scaleTitle?: LocalizedString;
  scaleSubtitle?: LocalizedString;
  scaleList?: Array<{
    _key: string;
  } & Card>;
  scaleBanner?: Banner;
  innovationTitle?: LocalizedString;
  innovationSubtitle?: LocalizedString;
  innovationStatsList?: Array<{
    _key: string;
  } & Card>;
  innovationList?: Array<{
    _key: string;
  } & Card>;
  innovationBanner?: Banner;
  communityTitle?: LocalizedString;
  communitySubtitle?: LocalizedString;
  communityStatsList?: Array<{
    _key: string;
  } & Card>;
  communityList?: Array<{
    _key: string;
  } & Card>;
  communityBanner?: Banner;
  eventsTitle?: LocalizedString;
  eventsSubtitle?: LocalizedString;
  eventsList?: Array<{
    _key: string;
  } & Event>;
  membershipsTitle?: LocalizedString;
  membershipsSubtitle?: LocalizedString;
  membershipsPlans?: Array<{
    _key: string;
  } & PricingPlan>;
  membershipsBanner?: Banner;
  contactTitle?: LocalizedString;
  contactSubtitle?: LocalizedString;
};

export type LocalizedString = {
  _type: "localizedString";
  en?: string;
};

export type Banner = {
  _type: "banner";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Seo = {
  _type: "seo";
  title?: LocalizedString;
  description?: LocalizedText;
  ogTitle?: LocalizedString;
  ogDescription?: LocalizedText;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  address?: LocalizedText;
  phone?: string;
  email?: string;
  workingHours?: Array<{
    days?: LocalizedString;
    hours?: string;
    _key: string;
  }>;
  mapEmbed?: string;
  socialLinks?: {
    instagram?: string;
    facebook?: string;
    youtube?: string;
    tiktok?: string;
    telegram?: string;
    whatsapp?: string;
  };
  defaultSeo?: Seo;
};

export type LocalizedText = {
  _type: "localizedText";
  en?: string;
};

export type PricingPlan = {
  _id: string;
  _type: "pricingPlan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  slug?: Slug;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  icon?: string;
  order?: number;
  isPopular?: boolean;
  pricing?: {
    perMonth?: number;
    perYear?: number;
  };
  features?: Array<{
    feature?: LocalizedString;
    icon?: string;
    isAvailable?: boolean;
    _key: string;
  }>;
  action?: Button;
};

export type Button = {
  _type: "button";
  text?: LocalizedString;
  link?: Link;
  icon?: string;
  iconPosition?: "left" | "right";
  variant?: "primary" | "secondary" | "outline" | "ghost" | "link" | "destructive" | "destructive-outline";
  className?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ContactFormSubmission = {
  _id: string;
  _type: "contactFormSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  message?: string;
  submittedAt?: string;
  status?: "new" | "read" | "replied" | "archived";
  notes?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  description?: LocalizedText;
  date?: string;
  endDate?: string;
  location?: LocalizedString;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<{
    _key: string;
  } & LocalizedString>;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  icon?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  stats?: Array<{
    _key: string;
  } & Card>;
  action?: Button;
  tags?: Array<{
    _key: string;
  } & LocalizedString>;
  featuresTitle?: LocalizedString;
  features?: Array<{
    _key: string;
  } & LocalizedString>;
};

export type Card = {
  _type: "card";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  icon?: string;
  tags?: Array<{
    _key: string;
  } & LocalizedString>;
  title?: LocalizedString;
  subtitle?: LocalizedString;
  description?: LocalizedText;
  primaryColor?: string;
  buttons?: Array<{
    _key: string;
  } & Button>;
};

export type Link = {
  _type: "link";
  href?: string;
  openInNewTab?: boolean;
  text?: LocalizedString;
  className?: string;
};

export type LocalizedRichText = {
  _type: "localizedRichText";
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Link>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = HomePage | LocalizedString | Banner | SanityImageCrop | SanityImageHotspot | Seo | Settings | LocalizedText | PricingPlan | Button | Slug | ContactFormSubmission | Event | Service | Card | Link | LocalizedRichText | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
